// فهرس الأسئلة والأجوبة — مستخرج من مجالس ألف باء الزواج

export const QA_INTRO = 'أسئلة مُستخرجة من مجالس ألف باء الزواج، مُنظَّمة حسب الموضوع مع رابط مباشر إلى موضع الإجابة في المجلس. اضغط على أيّ سؤال للانتقال إلى الإجابة الكاملة في سياقها الأصلي.';

export const QA_CATEGORIES = [
  {
    id: 'foundations',
    title: 'أساسيات الزواج والنكاح',
    icon: 'foundation',
    items: [
      {
        id: 'q-romantic-love',
        question: 'هل الحب الرومانسي المستمر ممكن في الزواج؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-السادس-والعشرون:-المودّة-والرحمة-والحبّ-الرومانسي',
      },
      {
        id: 'q-shared-interests',
        question: 'هل الاهتمامات المشتركة بين الزوجين مهمة؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الرابع-والعشرون:-الاهتمامات-المشتركة-بين-الزوجين',
      },
      {
        id: 'q-fatiha-marriage',
        question: 'هل قراءة الفاتحة تُعتبر زواجًا شرعيًّا؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الحادي-والثلاثون:-قراءة-الفاتحة-وعقد-القران-والزواج-الشرعي',
      },
      {
        id: 'q-lifecycle',
        question: 'كيف نفهم الدورة الحياتيّة والتحمّل في البدايات؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثاني-عشر:-الدورة-الحياتيّة-والتحمّل-في-البدايات-والنهايات',
      },
      {
        id: 'q-balanced-models',
        question: 'هل هناك فعلًا نماذج متزنة في الزواج؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '38.-نماذج-متوازنة-في-الزواج',
      },
    ],
  },
  {
    id: 'choosing',
    title: 'اختيار الشريك والتفرّس',
    icon: 'person_search',
    items: [
      {
        id: 'q-hijab-issue',
        question: 'ماذا لو كانت الفتاة على خير لكن حجابها ليس كاملًا؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثاني:-هل-موقف-واحد-يسبّب-النُّفرة-كافٍ-للتوقّف؟',
      },
      {
        id: 'q-shyness-vs-haya',
        question: 'كيف أميّز بين الحياء والخجل المرَضي عند الفتاة؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-السابع:-الفرق-بين-الحياء-والخجل-المرَضي',
      },
      {
        id: 'q-young-age',
        question: 'هل أخطب فتاة غير ناضجة بسبب صغر سنّها (١٨ سنة)؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثامن:-خِطبة-فتاة-غير-ناضجة-بسبب-صغر-السنّ-(18-سنة)',
      },
      {
        id: 'q-education-level',
        question: 'هل أتجاوز عن الدرجة التعليمية للطرف الآخر؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-التاسع:-هل-أقلّ-القليل-من-التعليم-يكفي-للتأهّل-للزواج؟',
      },
      {
        id: 'q-working-wife',
        question: 'كيف أعرف هل تناسبني الزوجة العاملة أم الماكثة في البيت؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-السابع-عشر:-الزوجة-العاملة-أم-الماكثة-في-البيت؟',
      },
      {
        id: 'q-addiction-question',
        question: 'هل من المناسب السؤال عن ملفّ الإدمان؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الخامس-والعشرون:-السؤال-عن-ملفّ-الإدمان',
      },
      {
        id: 'q-social-media-judge',
        question: 'هل يمكن الحكم على الشخص من منشوراته على وسائل التواصل؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '29.-الزواج-من-طالب-في-أوروبا',
      },
      {
        id: 'q-online-marriage',
        question: 'ما رأيكم في مواقع الزواج الإلكترونية؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '30.-مواقع-الزواج-الإلكترونية',
      },
    ],
  },
  {
    id: 'engagement',
    title: 'إدارة الخِطبة والتعارف',
    icon: 'handshake',
    items: [
      {
        id: 'q-long-engagement',
        question: 'ما حكم إطالة فترة الخِطبة أربع سنوات دون عقد قران؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-العاشر:-إطالة-فترة-الخِطبة-أربع-سنوات-دون-عقد-قران',
      },
      {
        id: 'q-remote-engagement',
        question: 'هل يُفضَّل عقد القران عن بُعد (المغترب)؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثالث-عشر:-عقد-القران-عن-بُعد-(المغترب-واليمنيّة)',
      },
      {
        id: 'q-red-lines-parents',
        question: 'هل أبيّن الخطوط الحمراء للأهل أم للطرف الآخر فقط؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثالث-والثلاثون:-بيان-الخطوط-الحمراء-للأهل-أم-للطرف-الآخر-فقط؟',
      },
      {
        id: 'q-rejection',
        question: 'كيف أرفض فتاة عُرضت عليّ دون إيذائها؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الخامس-والثلاثون:-كيف-أرفض-فتاة-عُرضت-عليّ-دون-إيذائها؟',
      },
      {
        id: 'q-return-after-rejection',
        question: 'كيف أتعامل مع الرغبة في العودة بعد الرفض؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-التاسع-عشر:-كيفية-التعامل-مع-الرغبة-في-العودة-بعد-الرفض',
      },
      {
        id: 'q-profile-card',
        question: 'ماذا يُكتَب في ورقة التعريف بالنفس قبل الزواج؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الخامس-عشر:-ماذا-يُكتَب-في-ورقة-التعريف-بالنفس؟',
      },
      {
        id: 'q-multiple-suitors',
        question: 'هل يجوز أن تجلس الفتاة مع خاطبَين في نفس الوقت؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '42.-تعدد-الخُطّاب-في-نفس-الوقت',
      },
    ],
  },
  {
    id: 'financial',
    title: 'الاستعداد المادي والنفقة',
    icon: 'payments',
    items: [
      {
        id: 'q-mahr',
        question: 'هل المهر تكريم للمرأة؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '14.-المهر:-تكريم-أم-قوامة؟',
      },
      {
        id: 'q-riba-loans',
        question: 'كيف يوازن الشاب بين ضعف دخله والابتعاد عن القروض الربوية؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '5.-الموازنة-بين-ضعف-الدخل-والابتعاد-عن-القروض-الربوية',
      },
      {
        id: 'q-wife-salary',
        question: 'هل من حق الزوجة ألا تشارك في مصاريف البيت؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '27.-مصروف-الزوجة-وراتبها',
      },
      {
        id: 'q-honeymoon',
        question: 'كيف أعرض فكرة رفض شهر العسل التقليدي على العروس؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثامن-عشر:-كيف-أعرض-فكرة-رفض-شهر-العسل-التقليدي-على-العروس؟',
      },
      {
        id: 'q-expensive-weddings',
        question: 'هل الأفراح الأكثر إنفاقًا أكثر عرضة للطلاق؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثامن-والعشرون:-علاقة-الإنفاق-المبالَغ-فيه-على-الأفراح-بالطلاق',
      },
      {
        id: 'q-living-with-parents',
        question: 'هل يجب السكن مع الوالدين؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '7.-السكن-مع-الأهل-أم-الاستقلال',
      },
      {
        id: 'q-job-stability',
        question: 'هل أتقدم للزواج وأنا غير مستقر وظيفيًّا؟',
        source: 'المجلس ٣٥',
        lectureSlug: 'lecture-35',
        sectionId: 'الاستقرار-الوظيفي:-هل-أتقدم-للزواج-وأنا-غير-مستقر؟',
      },
    ],
  },
  {
    id: 'psychology',
    title: 'النفس والصحة النفسية',
    icon: 'psychology',
    items: [
      {
        id: 'q-self-purification',
        question: 'هل يجب تزكية النفس بالكامل قبل الزواج؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الرابع:-تزكية-النفس-قبل-الزواج-ووهم-الكمال',
      },
      {
        id: 'q-anxiety',
        question: 'أعاني قلقًا شديدًا ورُهابًا اجتماعيًّا. هل هذا من معوّقات زواجي؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الخامس:-القلق-الشديد-والرهاب-الاجتماعي-وعلاقتهما-بالزواج',
      },
      {
        id: 'q-ocd',
        question: 'هل يجب أن أخبر خطيبتي باضطراب الوسواس القهري؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الحادي-عشر:-الوسواس-القهري-وإخبار-الزوجة-به',
      },
      {
        id: 'q-waswas-past',
        question: 'أعاني من وسواس بشأن العلاقات السابقة للمخطوبة، ما العلاج؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-السادس:-الوسواس-من-العلاقات-السابقة-للمخطوبة',
      },
      {
        id: 'q-sexual-readiness',
        question: 'كيف يعرف المرء أنّ الجانب الجنسي لن يكون عائقًا في الزواج؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثاني-والثلاثون:-كيف-يعرف-المرء-من-نفسه-أنّ-الجانب-الجنسي-لن-يكون-عائقًا-في-الزواج؟',
      },
    ],
  },
  {
    id: 'family',
    title: 'الأهل والعائلة',
    icon: 'family_restroom',
    items: [
      {
        id: 'q-mother-objection',
        question: 'الفتاة قابلة لكنّ أمّها تعترض على المستوى المادّي، ماذا أفعل؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الحادي-والعشرون:-موافقة-الفتاة-واعتراض-الأمّ-على-المستوى-المادّي',
      },
      {
        id: 'q-father-mahr',
        question: 'والدي يرفض أن يكون مهري أقل من قريباتي، ماذا أفعل؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '40.-رفض-الأهل-لتقليل-المهر',
      },
      {
        id: 'q-sufi-family',
        question: 'إذا كان عند أسرة الفتاة مسحة صوفيّة، هل يكون هذا خطًّا أحمر؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الرابع-عشر:-المسحة-الصوفيّة-عند-أسرة-الفتاة----خطّ-أحمر؟',
      },
      {
        id: 'q-living-with-inlaws',
        question: 'هل السكن مع أهل زوج غير ملتزمين يشكّل مشكلة للتربية؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '41.-السكن-مع-أهل-الزوج-غير-الملتزمين',
      },
    ],
  },
  {
    id: 'past-repentance',
    title: 'التوبة والماضي',
    icon: 'restart_alt',
    items: [
      {
        id: 'q-past-relationship',
        question: 'كنتُ في علاقة محرّمة ثم تبت، هل يجب أن أتزوّجها؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-العشرون:-الوعد-بالزواج-بعد-التوبة-من-علاقة-محرّمة',
      },
    ],
  },
  {
    id: 'married-life',
    title: 'الحياة الزوجية',
    icon: 'home',
    items: [
      {
        id: 'q-husband-time',
        question: 'هل من غير المقبول أن ينشغل الزوج عن زوجته ٤ ساعات بعد العمل؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-الثاني-والعشرون:-حقّ-الزوجة-في-وقت-الزوج-بعد-العمل',
      },
      {
        id: 'q-nushuz',
        question: 'ما مفهوم النشوز؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '36.-مفهوم-النشوز',
      },
      {
        id: 'q-extravagant-husband',
        question: 'زوجي مسرف ماديًّا وأنا لا أحبّ ذلك، كيف أتعامل؟',
        source: 'المجلس ٣٣',
        lectureSlug: 'lecture-33',
        sectionId: '34.-الزوج-المسرف',
      },
    ],
  },
  {
    id: 'music-wedding',
    title: 'العرس والاحتفالات',
    icon: 'celebration',
    items: [
      {
        id: 'q-music-wedding',
        question: 'هل يمكن إقامة عرس بدون موسيقى؟',
        source: 'المجلس ١٤',
        lectureSlug: 'lecture-14',
        sectionId: 'السؤال-السادس-عشر:-الموسيقى-في-حفل-الزفاف',
      },
      {
        id: 'q-convince-family-wedding',
        question: 'كيف أقنع الأهل بنمط الزفاف الذي أريده؟',
        source: 'المجلس ٣٥',
        lectureSlug: 'lecture-35',
        sectionId: 'كيف-أقنع-الأهل-بنمط-الزفاف-الذي-أريده؟',
      },
    ],
  },
];
